---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: cloudy
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.image.name }}-container
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: AUTHOR
          value: {{ .Values.env.author }}

---
apiVersion: v1
kind: Service
metadata:
  name: cloudy-cluster-ip
  namespace: cloudy
  labels:
    app: {{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 8000
  